#!/usr/bin/env bash

./scripts/go_executable_build.sh -S || exit 1  # dynamic builds are faster for debug iteration...
#make linux_static || exit 1  # dynamic builds are faster for debug iteration...
./test/deploy.sh -B -N testnet -v -C ./test/configs/testnet-nodes.txt
